# INTRODUÇÃO

Este parecer trata de uma opinião pessoal do sócio Luiz Fernando P. Droubi
acerca das contas da VEYRON EMPREENDIMENTO IMOBILIARIO SPE LTDA.

## Objetivo

Este parecer tem o objetivo de tão somente de auxililar o Conselho Fiscal da
VEYRON EMPREENDIMENTO IMOBILIARIO SPE LTDA. na análise dos balanços, balancetes,
notas fiscais e demais documentos apresentados pelo administradores ao longo
dos anos de 2022 a 2025. Este parecer não tem qualquer poder vinculante, ou seja,
Conselheiros Fiscais devem fazer suas próprias análises e determinar se darão
parecer para a aceitação ou rejeição das contas apresentadas pela administração
do empreendimento, *independentemente* da recomendação final deste parecer.

# METODOLOGIA

Neste parecer foi adotada a metodologia de análise aleatória dos documentos
apresentados pela empresa, com o intuito de identificar eventuais desvios, 
equívocos e não-conformidades nas contas apresentadas.

# ACHADOS

## Sobre o contrato

No início de 2022 os administradores disponibilizaram ao Conselho Fiscal da
VEYRON EMPREENDIMENTO IMOBILIARIO SPE LTDA. uma série de documentos visando
obter a aprovação das contas dos administradores desde a abertura da empresa, em
2018, até o ano de 2021. Dentre os documentos apresentados encontrava-se o
contrato de empreitada global constante do [ANEXO I], datado de 04/12/2019
(quatro de dezembro de dois mil e dezenove), em que a VEYRON EMPREENDIMENTO
IMOBILIÁRIO SPE LTDA efetuava a contratação da **Silveira Prestação de Serviços
em obras de Alvenaria LTDA.**, de nome fantasia DJ LOCAÇÂO DE MÃO DE OBRA, em
que constava uma planilha de atividades na cláusula 4 deste contrato, às páginas
3 e 4, definidora do preço total do contrato, de R$ 2.931.394,67.
Adicionalmente, os administradores forneceram um termo aditivo contratual,
datado de 11/02/2020 (onze de fevereiro de dois mil e vinte), como se pode
verificar no [ANEXO II], em que  são aditivados ao contrato de empreitada global
as atividades de:

- FORRO DE GESSO/MADEIRA
- PAVIMENTAÇÃO EXTERNA E PASSEIO EXTERNO
- RECUPERAÇÃO DO ENTORNO/VIZINHANÇA

Tais serviços totalizavam R$ 147.121,68, de forma que no parágrado único da 
cláusula primeira afirma que, "como consequência, o valor 
do contrato descrito no caput da Cláusula 4 passa a aser de R$ 3.078.516,35 
(Três milhões setenta e oito mil quinhentos e dezesseis reais e trinta e cinco 
centavos)."

Para nossa surpresa, contudo, neste último mês os administradores forneceram
uma pasta contendo um documento denominado "Contrato Veyron DJ - Assinado.pdf",
que pode ser visto no [ANEXO III], datado de 02/12/2019 (dois de dezembro de
dois mil e dezenove), no geral muito similar ao contrato anteriormente fornecido,
porém no qual em sua cláusula 4 - Preço e Forma de Pagamento, consta uma planilha
de atividades que somam R$ 3.078.516,35 (Três milhões setenta e oito mil 
quinhentos e dezesseis reais e trinta e cinco centavos), exatamente o mesmo
preço do contrato primeiramente divulgado após a assinatura do seu termo adivito,
em fevereio de 2020. Na planilha de atividades deste contrato ora apresentado,
nota-se a presença dos serviços de Gesso, Pavimentação Externa, Passeio Externo
e Recuperação do Entorno, serviços estes que não constavam do contrato
originalmente apresentado em 2022 ([ANEXO I]), mas que haviam sido objeto do
aditamento contratual de fevereiro de 2020, conforme [ANEXO II].

Conforme já apresentado em parecer do Conselho Fiscal em maio de 2022, é curioso
que foi faturado á DJ Locação de Mão de Obra, empresa contratada para o serviço
de empreitaga global, tenha faturado em dezembro de dois mil e dezenove, portanto
antes da celebração do termo aditivo contratual, de fevereiro de 2020, valor
idêntico ao celebrado neste termo, de R$ 147.121,68 (cento e quarenta e sete
mil cento e vinte um reais e sessenta e oito centavos), através da nota fiscal
n.º 240, de emitida em 20/12/2019 (vinte de dezembro de dois mil e dezenove).

Também é interessante notar que, em notificição extrajudicial enviada pelos
advogados da *Rubens Maciel Advocacia e Consultoria Preventiva*, representantes
da DJ Locação de Mão de Obra, o notificante, alega-se que "em 04 de dezembro de
2019", as partes entabularam 'contrato particular de mão-de-obra'". Mais à
frente, alega-se que o valor total do contrato foi estipulado em R$ 2.931.394,67
(dois milhões, novecentos e trinta e um mil, trezentos).

Ainda deve ser notado que o contrato primeiramente firmado em dois de dezembro
de 2019 é tratado com a **Construsousa Prestação de Serviços em Obras de
Alvenaria LTDA**, que tinha como representante legal o senhor Daniel Silveira de
Souza, CPF 797.201.779-00, sendo que o segundo contrato foi firmado com
a **Silveira Prestação de Serviços em obra de alvenaria LTDA.**, representada
pelo Sr. João Batista José de Souza, CPF 986.257.219-15.

Não se sabe se ambas as empresas pertencem a um mesmo grupo empresarial, mas o 
que fica claro é que os administradores da Veyron vinham negociando o contrato 
de empreitada global naqueles dias e tinham conhecimento completo da necessidade
de execução de todos os serviços necessários para a completa execução do 
empreendimento, porém por motivo desconhecido eles retiraram alguns destes
serviços do escopo contratual e depois voltaram com estes serviços na forma de
aditivos contratuais, no montante de aprox. 5% do valor global do contrato.

Se já era muito suspeito o pagamento antecipado de valor equivalente ao aditivo
contratual, cujos serviços são serviços finais da obra, de forma tecipada, antes
do início efetivo dos serviços, agora que vem à tona que os administradores já
sabiam da necessidade de execução dos serviços que foram objeto do termo aditivo
ainda em dezembro de 2019, por óbvio, por que então os administradores retiraram
estes serviços do escopo contratual, para depois reinserí-los através de um
aditivo contratual, firmado após o pagamento de igual montante de forma
antecipada?

## Sobre as medições

Os administradores entregaram um resumo de medições, que pode ser visto no
[ANEXO V]. No entanto, este resumo de medições apresenta uma coluna, denominada
**BRUTO NF**, que não representa a realidade dos faturamentos da empreiteira.
Para exemplificar, até fevereiro de 2020, período em que o contrato ainda não
havia sofrido reajuste, o faturamento da empreiteira já havia sido de 
R$ 400.999,96. Porém, o resumo de medições até esta mesma data mostra que haviam
sido medidos apenas R\$ 66.676,55 em serviços, tendo sido faturados 
R\$ 60.008,98, o que não corresponde à realidade dos faturamentos realmente
realizados. Esta observações é importante pois os reajustes contratuais devem
ser feitos apenas sobre o saldo contratual. 

## Sobre as subempreitas

Em seis de janeiro de 2020, portanto praticamente na mesma época da assinatura
do contrato de empreitada global, a empreiteira global de mão-de-obra assinou
contratos de subempreita com a Dival Otacílio Latronico Junior e com a R&E
Instalações Hidráulicas LTDA, em flagrante desacordo ao estabelecido no
parágrafo terceiro da cláusula 5 do contrato de empreitada global, "salvo com
prévia e expressa autorização por escrito do CONTRATANTE, inclusive com a 
anuência do instrumento contratual ...". A anuência por escrito da CONTRATANTE
não foi disponibilizada, porém, dado os fatos, os administradores anuíram as
subcontratações. Ocorre, portanto, que os administradores deveriam, então, 
no mesmo ato, descontar do contrato do empreiteiro valor igual à soma das
subcontratações, já que os pagamentos aos subempreiteiros seriam feitos 
diretamente pela CONTRATANTE, porém isto não é o que consta nas medições dos
serviços. Deve-se levar em conta, portanto, que as subempreitas apenas
interessaram à CONTRATADA, sem vantagem alguma à CONTRATANTE, pois: (a) a
CONTRATADA deixa de arcar com a tributação do recebimento dos valores dos
subempreiteiros, que é feito diretamente a estes, sem passar pela CONTRATADA.

Por óbvio, o contrato de prestação de serviços por empreitada pressupõe a 
existência de um BDI (Benefícios e Despesas Indiretas), no qual está inclusa um
percentual relativo aos impostos a serem pagos pela CONTRATADA. Se a CONTRATADA
não tem estes custos, natural é que estes custos a menor fossem descontados dos
pagamentos à CONTRATADA, mas isto não foi feito pelos administradores, mais uma
vez favorecendo a CONTRATADA.

Além das subempreitas referentes às instalações elétricas e hidráulicas, foi
detectado que foram contratados à parte serviços de pintura, instalação de
revestimentos cerâmicos, carpintaria, serralheria e mesmo serviços de 
pedreiros, todos serviços que deveriam, por contrato, ser realizados pelo
CONTRATADO da empreitada global, DJ Locação de mão de obra. As notas fiscais 
destes serviços extras encontram-se em anexo.

## Sobre a soma dos serviços encontrados

Após a consolidação das notas fiscais encontradas por este parecerista, foi
detectado que os valores totais faturados por cada empresa contra a VEYRON
EMPREENDIMENTO IMOBILIARIO SPE LTDA, até o final do ano de 2023, somam R$
3.431.357,97, compostos das seguintes parcelas:

1. **Faturamente direto ao empreiteiro de mão-de-obra**: R$ 2.805.002,93
2. **Faturamento ao subempreiteiro de instalações elétricas**: R$ 122.533,96
3. **Faturamento ao subempreiteiro de instalações hidráulicas**: R$ 104.132,31
4. **Crisborba Pinturas Eireli**: R$ 179.534,31
5. **Ismael Luiz da Silva (serviços de pintura)**: R$ 13.000,00
6. **Eliezer da Cruz Rocha (gesso)**: R$ 51.231,00
7. **Silva Revestimento Ceramica LTDA**: R$ 66.226,65
8. **Paulo Cesar Severino (serviços de pedreiro independente)**: R$ 86.696,81


O total faturado é maior do que o valor encontrado pela totalização da coluna
**BRUTO NF** do Resumo de Medições apresentado pelos administradores ([ANEXO
V]), que apresenta valor de R$ 3.273.402,84.

Os números acima demonstram que os administradores provavelmente fizeram uso do
mesmo *modus operandi* utilizado no superfaturamento dos projetos, que foram
pagos duas vezes: a quem realmente os executou, e depois a si mesmos. No caso,
os administradores pagaram os prestadores de serviços que deveriam ter sido
realizados pela empreiteira de forma avulsa, e pagaram novamente os serviços
realizados ao empreiteiro.

Ainda, há de se considerar que não havia motivo para a contratação avulsa de 
serviços que já estavam contratados junto ao empreiteiro de mão-de-obra. A
alegação de membros do conselho de que os pagamentos foram feitos a terceiros
para evitar bitributação é absurda: primeiramente, como mostram as notas fiscais,
muitos dos serviços prestados tiveram pagamento líquido igual ao valor bruto da
nota fiscal, por conta de empresas optantes pelo Sistema de Tributação Simples.
Segundo, como já afirmado neste parecer anteriormente, os tributos já eram 
esperados pelo empreiteiro no momento da assinatura do contrato. Portanto, é
claro que os tributos já estavam na composição do BDI (Benefícios e Despesas 
Indiretas) do empreiteiro, sendo absurdo o pagamento diretamente a terceiros
para "evitar tributação", como alegou um dos atuais membros do conselho fiscal
da VEYRON EMPREENDIMENTO IMOBILIARIO SPE LTDA.

Outro membro atual do Conselho Fiscal da VEYRON EMPREENDIMENTO IMOBILIARIO SPE 
LTDA, engenheiro civil renomado, alegou que não vê nas movimentações nenhuma
atipicidade. Isto consta, inclusive, dos pareceres apresentados pelo 
Conselho Fiscal em assembleia em que tentou-se aprovar as contas dos 
administradores, para nossa surpresa, apesar de tantas evidências de desvios
de recursos. Segundo este atual membro do conselhe fiscal:

> Como todos sabem me envolvi de perto neste processo de acompanhamento dos 
serviços da GDI na administração do Veyron. Tive acesso, assim como todos vocês 
aos balances, notas fiscais, contratos. Fiz o comparativo com obras que 
acompanho em minha atividade profissional. Não consegui identificar 
irregularidades que me façam não dar parecer favorável ao encerramento da 
contabilidade da SPE. Isto não quer dizer que ainda não tenhamos 
responsabilidades como é o caso de sistemas construtivos que precisam ainda ser
finalizados a contento. 

É de estranhar essa declaração, quando se analisa contrastando com outra
manifestação do próprio conselheiro, quando este ainda não era um membro do
Conselho Fiscal, mas já ciente de diversas irregularidades cometidas pelos
administradores, declarou que haver conflito de interesse flagrante o fato dos
administradores serem também os executores da obra ao mesmo tempo. Nas palavras
deste atual conselheiro à época, isto ocorreu por excesso de confiança
depositado na GDI por ele conhecer previamente dois dos administradores, a
saber, Fábio Elias e Rodrigo Zeggio.

Por fim, deve-se considerar ainda que todos os serviços que seriam prestados
pelo empreiteiro global, DJ Locação de mão de obra, deveriam, por força da
cláusula 5 do contrato, ser realizados por empregados devidamente registrados,
"correndo por sua conta as despesas com salários, previdência social, FGTS,
seguro de acidentes, toda e qualquer obrigação trabalhista, (devendo apresentar
guias quitadas mensalmente, inclusive a GFIP e a RE - Relação de Empregados)
como também, se houver, as despesas com alimentação e transporte de seus
funcionários até o local da obra."

Ora, ao contratar serviços prestados por terceiros, obviamente que a CONTRATADA
não incorreu com os custos trabalhistas previstos. Mais grave, sequer a
CONTRATADA correu os riscos trabalhistas (risco de afastamento, de indenizações
decorrentes de acidente de trabalho, etc.), haja vista a contratação direta por
parte da VEYRON EMPREENDIMENTO IMOBILIARIO SPE LTDA. Os administradores, assim,
ao realizar a contratação direta de prestadores de serviços, acabaram por
tornar inútil uma das maiores razões da contratação de um empreiteiro global de
mão-de-obra, que é blindar o empreendimento contra os riscos trabalhistas
da natureza destes serviços.

## Sobre a taxa de administração

Os administradores, mais uma vez, contando com a saída temporária do quadro
societário do sócio Luiz Fernando Palin Droubi, em 2023, passaram novamente a
remunerar-se fartamente do caixa da empresa à título de administração de obras.
Os problemas de superestimação dos custos de obra para inflação da taxa de 
administração já foram demonstrados em pareceres anteriores e já havia sido
deixado claro para os administradores a necessidade de, primeiramente, de parar
a remuneração do seu contrato e, o que também é necessário, mas infelizmente
não foi dado prosseguimento pelos atuais membros do conselho, a devolução das
taxas cobradas a maior.

Assim, durante o ano de 2023 os admnistradores remuneraram-se fartamente, da 
seguinte forma:

| Data       | NF   | Valor Bruto | Valor Líquido |
|:-----------|-----:|------------:|--------------:|
| 04/05/2023 | 270  | 69.515,82   | 63.155,12     |
| 04/06/2023 | 275  | 70.468,49   | 64.020,62     |
| 03/07/2023 | 279  | 32.188,60   | 29.243,34     |
| 01/08/2023 | 283  | 32.188,60   | 29.243,34     |
| 01/09/2023 | 287  | 32.188,60   | 29.243,34     |
| TOTAL             | 236.550,10  | 214.905,80    |   
|: Faturamento da GDI Empreendimentos contra a VEYRON SPE durante 2023.


Questionados os conselheiros, um deles respondeu que "*alguns dos valores 
citados de pagto a GDI retornaram ao caixa da SPE*". Ora, primeiramente causa
espanto que o conselheiro e seus pares tratem como suficiente que *alguns* dos
valores tenha retornado, eventualmente, ao caixa da SPE. 

Ao se analisar-se o Resumo do contrato de administração fornecido pelos
administradores (ver [ANEXO VI]), nota-se que houve uma alegada devolução de
apenas R$ 143.270,51 (cento e quarenta e três mil duzentos e setenta reais e
cinquenta e um centavos), realizado alegadamente em 26/10/2023.

Diversos esclarecimentos são necessários, deve-se colocar: por que chegou-se a
este valor de devolução, e não houve a devolução integral dos valores pagos?
Sobre a devolução, houve cancelamento de nota fiscal emitida? O Conselho deve
estar sempre atentos à movimentações que possam levantar suspeitas de lavagem de
capitais.




